### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ThangHuuVu** [ThangHuuVu/vintage-camera-showcase#1]
**Is your feature request related to a problem? Please describe.**
Update README.md to describe the project.

**Describe the solution you'd like**
Write down about this project:
- Motivation
- Technologies

**Describe alternatives you've considered**

**Additional context**

**Comment by ducpham163** [comment]
abc

**Comment by ThangHuuVu** [comment]
Closed as README.md is updated directly to `main`
